//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBookRequest", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Contracts.Request")]
    public partial class CreateBookRequest : object
    {
        
        private int AuthorIdField;
        
        private string NameField;
        
        private System.DateTime PublishDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorId
        {
            get
            {
                return this.AuthorIdField;
            }
            set
            {
                this.AuthorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishDate
        {
            get
            {
                return this.PublishDateField;
            }
            set
            {
                this.PublishDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookDisplayModel", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Contracts.Response")]
    public partial class BookDisplayModel : object
    {
        
        private string AuthorField;
        
        private string BookStateField;
        
        private int IdField;
        
        private System.DateTime InitDateField;
        
        private string NameField;
        
        private System.DateTime PublishDateField;
        
        private string WhoChangedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookState
        {
            get
            {
                return this.BookStateField;
            }
            set
            {
                this.BookStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitDate
        {
            get
            {
                return this.InitDateField;
            }
            set
            {
                this.InitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishDate
        {
            get
            {
                return this.PublishDateField;
            }
            set
            {
                this.PublishDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoChanged
        {
            get
            {
                return this.WhoChangedField;
            }
            set
            {
                this.WhoChangedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Domain.Models")]
    public partial class Book : object
    {
        
        private int AuthorIdField;
        
        private int BookStateIdField;
        
        private int IdField;
        
        private System.DateTime InitDateField;
        
        private string NameField;
        
        private System.DateTime PublishDateField;
        
        private string WhoChangedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorId
        {
            get
            {
                return this.AuthorIdField;
            }
            set
            {
                this.AuthorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookStateId
        {
            get
            {
                return this.BookStateIdField;
            }
            set
            {
                this.BookStateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitDate
        {
            get
            {
                return this.InitDateField;
            }
            set
            {
                this.InitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishDate
        {
            get
            {
                return this.PublishDateField;
            }
            set
            {
                this.PublishDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoChanged
        {
            get
            {
                return this.WhoChangedField;
            }
            set
            {
                this.WhoChangedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IBookStore")]
    public interface IBookStore
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/TestConnection", ReplyAction="http://tempuri.org/IBookStore/TestConnectionResponse")]
        System.Threading.Tasks.Task<ServiceReference.TestConnectionResponse> TestConnectionAsync(ServiceReference.TestConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/TestDbConnection", ReplyAction="http://tempuri.org/IBookStore/TestDbConnectionResponse")]
        System.Threading.Tasks.Task<ServiceReference.TestDbConnectionResponse> TestDbConnectionAsync(ServiceReference.TestDbConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/CreateBook", ReplyAction="http://tempuri.org/IBookStore/CreateBookResponse")]
        System.Threading.Tasks.Task<ServiceReference.CreateBookResponse> CreateBookAsync(ServiceReference.CreateBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/RemoveBook", ReplyAction="http://tempuri.org/IBookStore/RemoveBookResponse")]
        System.Threading.Tasks.Task<ServiceReference.RemoveBookResponse> RemoveBookAsync(ServiceReference.RemoveBookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestConnection", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestConnectionRequest
    {
        
        public TestConnectionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestConnectionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TestConnectionResult;
        
        public TestConnectionResponse()
        {
        }
        
        public TestConnectionResponse(string TestConnectionResult)
        {
            this.TestConnectionResult = TestConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestDbConnection", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestDbConnectionRequest
    {
        
        public TestDbConnectionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestDbConnectionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestDbConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TestDbConnectionResult;
        
        public TestDbConnectionResponse()
        {
        }
        
        public TestDbConnectionResponse(string TestDbConnectionResult)
        {
            this.TestDbConnectionResult = TestDbConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBook", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.CreateBookRequest newBook;
        
        public CreateBookRequest1()
        {
        }
        
        public CreateBookRequest1(ServiceReference.CreateBookRequest newBook)
        {
            this.newBook = newBook;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBookResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.BookDisplayModel CreateBookResult;
        
        public CreateBookResponse()
        {
        }
        
        public CreateBookResponse(ServiceReference.BookDisplayModel CreateBookResult)
        {
            this.CreateBookResult = CreateBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveBook", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveBookRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public RemoveBookRequest()
        {
        }
        
        public RemoveBookRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveBookResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveBookResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.Book RemoveBookResult;
        
        public RemoveBookResponse()
        {
        }
        
        public RemoveBookResponse(ServiceReference.Book RemoveBookResult)
        {
            this.RemoveBookResult = RemoveBookResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IBookStoreChannel : ServiceReference.IBookStore, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BookStoreClient : System.ServiceModel.ClientBase<ServiceReference.IBookStore>, ServiceReference.IBookStore
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BookStoreClient() : 
                base(BookStoreClient.GetDefaultBinding(), BookStoreClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBookStore.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookStoreClient(EndpointConfiguration endpointConfiguration) : 
                base(BookStoreClient.GetBindingForEndpoint(endpointConfiguration), BookStoreClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookStoreClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BookStoreClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookStoreClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BookStoreClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.TestConnectionResponse> TestConnectionAsync(ServiceReference.TestConnectionRequest request)
        {
            return base.Channel.TestConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.TestDbConnectionResponse> TestDbConnectionAsync(ServiceReference.TestDbConnectionRequest request)
        {
            return base.Channel.TestDbConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CreateBookResponse> CreateBookAsync(ServiceReference.CreateBookRequest1 request)
        {
            return base.Channel.CreateBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RemoveBookResponse> RemoveBookAsync(ServiceReference.RemoveBookRequest request)
        {
            return base.Channel.RemoveBookAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBookStore))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBookStore))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/WcfBookShop/BookStore.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BookStoreClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBookStore);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BookStoreClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBookStore);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBookStore,
        }
    }
}
